version: '3'

services:

    app:
        build: .
        container_name: app
        volumes:
            - ./laravel:/var/www
        networks: 
            - app-network

    nginx:
        #build from Dockerfile from dir .docker/nginx
        build: .docker/nginx
        container_name: nginx
        #restart in case of failure
        restart: always
        #enables iteractive access
        tty: true
        #redirect computer 8080 port to 80 port from nginx
        ports:
            - "8080:80"
        volumes:
            - ./laravel:/var/www
        networks: 
            - app-network            

    db:
        image: mysql:5.7
        #avoid errors of file types
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./.docker/dbdata:/var/lib/mysql
        ports:
            - "33006:3306"
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks: 
            - app-network
    
    redis:
        image: redis:alpine
        expose:
            - 6379
        networks: 
            - app-network
        container_name: redis
    
networks:
    app-network:
        driver: bridge    