version: '3'

services:

    app:
        build: .
        container_name: app
        # entrypoint: dockerize -template ./.docker/app/.env:./laravel/.env -wait tcp://db:3306 -timeout 120s php-fpm
        # entrypoint: dockerize -wait tcp://db:3306 -timeout 120s ./.docker/entrypoint.sh
        # environment:
        #     - DB_HOST=db
        #     - DB_DATABASE=laravel
        #     - DB_USERNAME=root        
        #     - DB_PASSWORD=root                    
        volumes:
            - ./laravel:/var/www
        networks: 
            - app-network
        depends_on: 
            - db
            - redis

    nginx:
        #build from Dockerfile from dir .docker/nginx
        build: .docker/nginx
        container_name: nginx
        #restart in case of failure
        restart: always
        #enables iteractive access
        tty: true
        #redirect computer 8080 port to 80 port from nginx
        ports:
            - "8080:80"
        volumes:
            - ./laravel:/var/www
        networks: 
            - app-network            
        depends_on: 
            - app
        environment:
            - APP_HOST=app
            - APP_PORT=9000

    db:
        image: mysql:5.7
        #avoid errors of file types
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./.docker/dbdata:/var/lib/mysql
        ports:
            - "33006:3306"
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks: 
            - app-network
    
    redis:
        image: redis:alpine
        expose:
            - 6379
        networks: 
            - app-network
        container_name: redis
    
networks:
    app-network:
        driver: bridge    